import 'package:flutter/material.dart';

enum GameDifficulty {
  normal,
  spicy,
  hot,
}

class DifficultyOption {
  final GameDifficulty difficulty;
  final String name;
  final String emoji;
  final Color color;
  final List<String> truthPrompts;
  final List<String> darePrompts;

  const DifficultyOption({
    required this.difficulty,
    required this.name,
    required this.emoji,
    required this.color,
    required this.truthPrompts,
    required this.darePrompts,
  });

  static const List<DifficultyOption> options = [
    DifficultyOption(
      difficulty: GameDifficulty.normal,
      name: 'Normal',
      emoji: '😊',
      color: Colors.green,
      truthPrompts: [
        // Personal questions
        '¿Cuál es tu mayor miedo?',
        '¿Cuál ha sido tu momento más vergonzoso?',
        '¿Cuál es tu sueño más grande?',
        '¿Cuál es tu talento oculto?',
        '¿Cuál es tu recuerdo más feliz?',
        '¿Qué superpoder te gustaría tener?',
        '¿Cuál es tu lugar favorito en el mundo?',
        '¿Cuál es tu película favorita y por qué?',
        '¿Qué te hace reír sin control?',
        '¿Cuál es tu comida favorita?',
        '¿Cuál es tu recuerdo de infancia más preciado?',
        '¿Qué harías si tuvieras un millón de dólares?',
        '¿Cuál es la cosa más loca que has hecho por diversión?',
        '¿Cuál es tu mayor logro hasta ahora?',
        '¿Qué te gustaría cambiar de ti mismo?',
        '¿Cuál es tu mayor arrepentimiento?',
        '¿Qué te hace sentir nostálgico?',
        '¿Cuál es tu mayor meta en la vida?',
        '¿Qué te hace sentir realmente vivo?',
        '¿Cuál es tu mayor fortaleza?',
      ],
      darePrompts: [
        // Fun challenges
        'Haz 10 flexiones ahora mismo',
        'Haz 20 sentadillas ahora mismo',
        'Haz una pose de yoga graciosa',
        'Baila la macarena completa',
        'Haz jumping jacks por 30 segundos',
        'Mantén el equilibrio en un pie por 30 segundos',
        'Haz tu mejor pose de superhéroe',
        'Intenta hacer el split',
        'Haz 10 abdominales',
        'Baila como robot por 30 segundos',
        'Imita a un animal durante 30 segundos',
        'Canta el estribillo de tu canción favorita',
        'Cuenta un chiste malo',
        'Haz tu mejor imitación de un famoso',
        'Haz una voltereta (si es seguro)',
        'Habla con acento extranjero por 2 minutos',
        'Haz una cara graciosa y mantente así por 30 segundos',
        'Inventa un baile tonto y enséñaselo al grupo',
        'Haz una parodia de un anuncio de TV',
        'Actúa como si fueras un zombie por 1 minuto',
      ],
    ),
    DifficultyOption(
      difficulty: GameDifficulty.spicy,
      name: 'Spicy',
      emoji: '🌶️',
      color: Colors.orange,
      truthPrompts: [
        // Romance & Dating
        '¿Cuál es tu tipo ideal de pareja?',
        '¿Cuál ha sido tu peor cita?',
        '¿Alguna vez has tenido un amor platónico?',
        '¿Cuál es tu técnica de coqueteo?',
        '¿Cuál fue tu primer beso?',
        '¿Te has enamorado a primera vista?',
        '¿Qué es lo más romántico que has hecho?',
        '¿Cuál es tu idea de una cita perfecta?',
        '¿Has tenido algún crush con alguien del grupo?',
        '¿Qué es lo más atrevido que has hecho en una cita?',
        '¿Alguna vez has mentido para impresionar a alguien?',
        '¿Cuál es tu mayor turn-off en una pareja?',
        '¿Alguna vez has tenido sentimientos por el ex de un amigo?',
        '¿Cuál es tu mayor turn-on?',
        '¿Alguna vez has enviado un mensaje a la persona equivocada?',
        '¿Cuál es la cosa más vergonzosa que has hecho por amor?',
        '¿Alguna vez has tenido una aventura de una noche?',
        '¿Cuál es tu mayor inseguridad en una relación?',
        '¿Alguna vez has sido infiel?',
        '¿Qué es lo más loco que has hecho por celos?',
      ],
      darePrompts: [
        // Flirty challenges
        'Dale un abrazo a la persona de tu derecha',
        'Haz un cumplido sincero a cada persona del grupo',
        'Deja que alguien del grupo te peine como quiera',
        'Haz tu mejor cara seductora',
        'Cuenta una anécdota vergonzosa sobre tu última cita',
        'Imita cómo crees que besa la persona de tu izquierda',
        'Deja que alguien te dibuje algo en la cara',
        'Haz una llamada telefónica a alguien y dile lo mucho que lo extrañas',
        'Baila de forma seductora por 30 segundos',
        'Deja que alguien del grupo te dé un masaje en los hombros',
        'Muestra la última foto que te tomaste',
        'Muestra los últimos 5 mensajes de texto que has enviado',
        'Deja que el grupo revise tu historial de búsqueda',
        'Deja que alguien publique algo en tus redes sociales',
        'Haz una serenata a alguien del grupo',
        'Haz un baile de TikTok',
        'Deja que alguien te maquille con los ojos vendados',
        'Imita a otra persona del grupo hasta que alguien adivine quién es',
        'Cuenta una historia embarazosa sobre ti mismo',
        'Deja que alguien te dé de comer algo con los ojos vendados',
      ],
    ),
    DifficultyOption(
      difficulty: GameDifficulty.hot,
      name: 'Hot',
      emoji: '🔥',
      color: Colors.red,
      truthPrompts: [
        '¿Alguna vez te tentaste con alguien que no deberías?',
        'Si pudieras elegir un lugar inesperado para un encuentro, ¿cuál sería?',
        '¿Con qué famoso/a cumplirías una fantasía?',
        '¿Cuál fue el momento más caliente en un lugar público?',
        '¿Te animás a contar el sueño más erótico que tuviste?',
        'Si tuvieras que describir tu mejor experiencia en tres palabras, ¿cuáles serían?',
        '¿Alguna vez tuviste que disimular lo mucho que te gustaba alguien?',
        '¿Qué prenda de ropa te hace sentir más sexy?',
        '¿Te animaste a jugar con disfraces o todavía no te soltaste?',
        '¿Qué parte de tu cuerpo creés que más llama la atención?',
        'Si tuvieras que susurrarle algo provocador a alguien del grupo, ¿qué sería?',
        '¿Alguna vez alguien te mandó un mensaje subido de tono en el peor momento?',
        '¿Te animaste a mandar fotos atrevidas o preferís dejarlo a la imaginación?',
        '¿Alguna vez te arrepentiste de un mensaje hot?',
        'Si tuvieras que dar una clase sobre el arte de seducir, ¿qué consejo darías?',
        '¿Alguna vez alguien te pidió que hagas algo demasiado jugado?',
        '¿Tenés un gesto o una mirada que usás para seducir?',
        'Si pudieras revivir tu mejor experiencia, ¿lo harías igual o le sumarías algo más?',
        '¿Preferís la tensión antes de un beso o el momento en que finalmente pasa?',
        '¿Alguna vez hiciste una apuesta picante con alguien?',
      ],
      darePrompts: [
        'Mirá al jugador de tu izquierda y decile "te apuesto un beso a que no te animás a…"',
        'El grupo elige a alguien y tenés que susurrarle algo al oído que lo haga sonrojar',
        'Decile al jugador de tu derecha qué parte de su cuerpo besarías primero si pudieras',
        'El grupo elige a alguien y tenés que darle un beso en el cuello',
        'Mirá a los ojos al jugador de tu frente y decile "te imaginé en mi cama más de una vez"',
        'El jugador de tu izquierda tiene que decirte cómo le gustaría que lo/a beses y vos tenés que hacerlo',
        'Dejá que el jugador de tu derecha te susurre algo atrevido y reaccioná sin decir una palabra',
        'Tocá el cuello del jugador de tu frente suavemente y decile "qué ganas de morderte"',
        'Decile al jugador que el grupo elija qué harías si estuvieran solos en una habitación',
        'El jugador de tu derecha tiene que decirte una palabra caliente y vos responder con otra más intensa',
        'Pasale la mano por el muslo al jugador que el grupo elija y sostené la mirada',
        'Acariciá el cuello del jugador de tu izquierda y decile "si supieras lo que quiero hacerte ahora mismo"',
        'Besale la mano al jugador de tu frente y decile "prometo portarme mal"',
        'Dale un beso en la mejilla al jugador que el grupo elija, pero muy cerca de los labios',
        'Hacé contacto visual con el jugador de tu izquierda mientras mordés algo lentamente',
        'Decile al jugador de tu derecha qué parte de su cuerpo tocarías primero si estuvieran solos',
        'Tocá la nuca del jugador de tu frente mientras le decís "me encantás"',
        'Hablá en el oído del jugador de tu derecha y decile "quiero probarte"',
        'Llevate un dedo a los labios y hacé contacto visual con el jugador de tu izquierda',
        'Tocá los labios del jugador que el grupo elija con la yema de los dedos',
      ],
    ),
  ];
}